### ISSUE TITLE
ML Roadmap

### ISSUE THREAD

**Issue by HridayM25** [LPE-Labs/reDocs.ai#1]
This issue proposes several initiatives to improve the performance and capabilities of our current machine learning model:

- [ ] Investigate Alternative Embedding Models:  We are currently using CodeBERT, which has its own limitations. Contributors can look into exploring different embedding models, perhaps even look into training their own from a multimodal approach (NL/PL).
- [ ] Explore Different Context Specific Mechanisms : We are currently using a "window" algorithm to maintain context, which is not the most efficient technique. Contributors can look into memory networks, various attention mechanisms, or Reinforcement Learning with Memory.
- [ ] Dendrogram Feature : Based on the current clustering algorithm used, contributors can add this functionality. You can look into dendrograms [here](https://www.displayr.com/what-is-dendrogram/).
- [ ] Explore other Clustering Algorithms : Agglomerative Clustering was chosen to take an advantage of any hierarchical relation between the code clusters, but other more efficient or more meaningful clustering algorithms can be looked into.
- [ ] Investigate other LLMS : We are using ChatGPT 3.5 as of now, contributors can look at other LLMs which perform better.
